mysql:
  user: 'root'
  password: 'asdfasdf'
  host: localhost
  database: mememana
  port: 3306
  poolsize: 10
  connectionTimeout: 10000
  idleTimout: 600000
  maxLifetime: 7200000
manaRotTime: 30d
manaGainTimeout: 22h
manaWaitTime: 30m
maximumDailyMana: 10
pearledManaScale: 1
pearlRefillAmount: 
  EXILE: 1
  PRISON: 1
pearlupgradeAmount: 10
